name: "DJ Hello"

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main
      - master

jobs:
 hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          label: "needs-review"